line-length = 120

[lint]
select = ["E", "F", "W", "C", "D", "N", "T", "B"]
ignore = []  # no ignored rules

[lint.mccabe]
max-complexity = 8  # strict, quality code is required

[lint.pydocstyle]
convention = "google"

[format]
docstring-code-format = true
docstring-code-line-length = 120
